-- MySQL Script generated by MySQL Workbench
-- Sat Feb 23 10:45:57 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`roles` (
  `id` VARCHAR(32) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `clave` TINYINT(2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id` VARCHAR(32) NOT NULL,
  `nombre` VARCHAR(50) NULL,
  `correo` VARCHAR(50) NULL,
  `avatar` BLOB NULL,
  `rol` VARCHAR(32) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_idx` (`rol` ASC),
  CONSTRAINT `fk_usuario`
    FOREIGN KEY (`rol`)
    REFERENCES `mydb`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`post` (
  `id` VARCHAR(32) NOT NULL,
  `titulo` VARCHAR(100) NULL,
  `encabezado` VARCHAR(100) NULL,
  `descripcion` LONGTEXT NULL,
  `vistas` INT NULL,
  `fecha` DATETIME NULL,
  `usuario` VARCHAR(32) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_idx` (`usuario` ASC),
  CONSTRAINT `fk_usuario`
    FOREIGN KEY (`usuario`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`post_comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`post_comentario` (
  `id` VARCHAR(32) NOT NULL,
  `comentario` LONGTEXT NULL,
  `usuario` VARCHAR(32) NULL,
  `fecha` DATETIME NULL,
  `post` VARCHAR(32) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_idx` (`post` ASC),
  CONSTRAINT `fk_post`
    FOREIGN KEY (`post`)
    REFERENCES `mydb`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comentario_voto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comentario_voto` (
  `id` VARCHAR(32) NOT NULL,
  `positivo` TINYINT NULL,
  `comentario` VARCHAR(32) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_comentario`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`post_comentario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = DEFAULT;


-- -----------------------------------------------------
-- Table `mydb`.`post_imagen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`post_imagen` (
  `id` INT NOT NULL,
  `post` VARCHAR(32) NULL,
  `imagen` BLOB NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_idx` (`post` ASC),
  CONSTRAINT `fk_post`
    FOREIGN KEY (`post`)
    REFERENCES `mydb`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`encuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`encuesta` (
  `id` VARCHAR(32) NOT NULL,
  `nombre` VARCHAR(50) NULL,
  `descripcion` LONGTEXT NULL,
  `usuario` VARCHAR(32) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_idx` (`usuario` ASC),
  CONSTRAINT `fk_usuario`
    FOREIGN KEY (`usuario`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`encuesta_pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`encuesta_pregunta` (
  `id` VARCHAR(32) NOT NULL,
  `pregunta` VARCHAR(100) NULL,
  `respuesta1` VARCHAR(45) NULL,
  `respuesta2` VARCHAR(100) NULL,
  `respuesta3` VARCHAR(100) NULL,
  `respuesta4` VARCHAR(100) NULL,
  `respuesta5` VARCHAR(100) NULL,
  `encuesta` VARCHAR(32) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_encuesta_idx` (`encuesta` ASC),
  CONSTRAINT `fk_encuesta`
    FOREIGN KEY (`encuesta`)
    REFERENCES `mydb`.`encuesta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`encuesta_respuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`encuesta_respuesta` (
  `id` VARCHAR(32) NOT NULL,
  `respuesta` INT NULL,
  `pregunta` VARCHAR(32) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pregunta_idx` (`pregunta` ASC),
  CONSTRAINT `fk_pregunta`
    FOREIGN KEY (`pregunta`)
    REFERENCES `mydb`.`encuesta_pregunta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`redes_sociales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`redes_sociales` (
  `id` VARCHAR(32) NOT NULL,
  `usuario` VARCHAR(32) NULL,
  `facebook` VARCHAR(50) NULL,
  `twitter` VARCHAR(50) NULL,
  `instagram` VARCHAR(50) NULL,
  `usuario` VARCHAR(32) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_idx` (`usuario` ASC),
  CONSTRAINT `fk_usuario`
    FOREIGN KEY (`usuario`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sesiones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sesiones` (
  `id` VARCHAR(32) NOT NULL,
  `usaurio` VARCHAR(32) NULL,
  `fecha` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_idx` (`usaurio` ASC),
  CONSTRAINT `fk_usuario`
    FOREIGN KEY (`usaurio`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
